version: '2'

services:
  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - traefik_default

  sparql:
    image: 6016ca8db0f0
    labels:
      - "traefik.backend=sparql"
      - "traefik.port=9999" # force to pick 9999 ignore the 8080 admin port
      - "traefik.frontend.rule=Host:opencore.dev;Method:GET,POST;PathPrefix:/blazegraph"
    networks:
      - traefik_default

  web:
    image: earthcube/cdfrwgweb:0.8
    labels:
      - "traefik.backend=web"
      - "traefik.frontend.rule=Host:opencore.dev"
    networks:
      - traefik_default

networks:
  traefik_default: